app:
    resource: "@AppBundle/Controller/"
    type:     annotation

grunt_homepage:
    path:     /
    defaults: { _controller: AppBundle:Grunt:show }
grunt_garaj:
    path:     /garaj
    defaults: { _controller: AppBundle:Grunt:show }
grunt_jurnal:
    path:     /jurnal
    defaults: { _controller: AppBundle:Grunt:show }
grunt_diy:
    path:     /diy
    defaults: { _controller: AppBundle:Grunt:show }

grunt_contact:
    path:     /contact
    defaults: { _controller: AppBundle:Grunt:contact }

grunt_register:
    path:     /register
    defaults: { _controller: AppBundle:Register:register}

grunt_admin:
    path:     /admin
    defaults: { _controller: AppBundle:Admin:newArticle}
grunt_list:
    path:     /list
    defaults: { _controller: AppBundle:Admin:listArticle}
grunt_delete:
    path:     /delete
    defaults: { _controller: AppBundle:Admin:deleteArticle}

grunt_user:
    path:     /user
    defaults: { _controller: AppBundle:Admin:listUser}

comment_garaj:
    path:     /comment/garaj
    defaults: { _controller: AppBundle:Comment:newComment}
comment_diy:
    path:     /comment/diy
    defaults: { _controller: AppBundle:Comment:newComment}
comment_jurnal:
    path:     /comment/jurnal
    defaults: { _controller: AppBundle:Comment:newComment}

security_login:
    path:     /login
    defaults: { _controller: AppBundle:Security:login}
security_logout:
    path:     /logout
    defaults: { _controller: AppBundle:Security:login}


