app:
    resource: "@AppBundle/Controller/"
    type:     annotation
elfinder:
     resource: "@FMElfinderBundle/Resources/config/routing.yml"

grunt_register:
    path:     /register
    defaults: { _controller: AppBundle:Register:register}

grunt_contact:
    path:     /contact
    defaults: { _controller: AppBundle:Grunt:contact }

grunt_admin:
    path:     /admin
    defaults: { _controller: AppBundle:Admin:newArticle}
grunt_list:
    path:     /list
    defaults: { _controller: AppBundle:Admin:listArticle}
grunt_edit:
    path:     /edit/{id}
    defaults: { _controller: AppBundle:Admin:editArticle}
grunt_delete:
    path:     /delete/{id}
    defaults: { _controller: AppBundle:Admin:deleteArticle}

grunt_user:
    path:     /user
    defaults: { _controller: AppBundle:Admin:listUser}
grunt_user_admin:
    path:     /adminuser/{id}
    defaults: { _controller: AppBundle:Admin:adminUser}
grunt_user_delete:
    path:     /deleteuser/{id}
    defaults: { _controller: AppBundle:Admin:deleteUser}

comment_garaj:
    path:     /comment/{page}
    defaults: { _controller: AppBundle:Comment:newComment}
response_garaj:
    path:     /response/{page}
    defaults: { _controller: AppBundle:Response:newCommentResponse}
comment_list:
    path: /listComments
    defaults: { _controller: AppBundle:Comment:listComment}
comment_edit:
    path:     /editcomment/{id}
    defaults: { _controller: AppBundle:Comment:editComment}
comment_delete:
    path:     /deletecomment/{id}
    defaults: { _controller: AppBundle:Comment:deleteComment}


security_login:
    path:     /login
    defaults: { _controller: AppBundle:Security:login}
security_logout:
    path:     /logout
    defaults: { _controller: AppBundle:Security:login}

grunt_homepage:
    path:     /
    defaults: { _controller: AppBundle:Grunt:show, id: null}

grunt_garaj:
    path:     /{page}
    defaults: { _controller: AppBundle:Grunt:show, id: null}
grunt_article:
    path: /{page}/{id}
    defaults: { _controller: AppBundle:Grunt:show }









