app:
    resource: "@AppBundle/Controller/"
    type:     annotation
elfinder:
     resource: "@FMElfinderBundle/Resources/config/routing.yml"

profile:
    path:     /profile/{id}
    defaults: { _controller: AppBundle:UserProfile:ShowProfile}

grunt_register:
    path:     /register
    defaults: { _controller: AppBundle:Register:register}

grunt_contact:
    path:     /contact
    defaults: { _controller: AppBundle:Grunt:contact }

article_new:
    path:     /article
    defaults: { _controller: AppBundle:Admin:newArticle}
article_list:
    path:     /list
    defaults: { _controller: AppBundle:Admin:listArticle}
article_edit:
    path:     /edit/{id}
    defaults: { _controller: AppBundle:Admin:editArticle}
article_view:
    path:     /view/{id}
    defaults: { _controller: AppBundle:Admin:viewArticle}
article_delete:
    path:     /delete/{id}
    defaults: { _controller: AppBundle:Admin:deleteArticle}

user_list:
    path:     /user
    defaults: { _controller: AppBundle:Admin:listUser}
user_admin:
    path:     /adminuser/{id}
    defaults: { _controller: AppBundle:Admin:adminUser}
user_standard:
    path:     /standarduser/{id}
    defaults: { _controller: AppBundle:Admin:standardUser}
user_delete:
    path:     /deleteuser/{id}
    defaults: { _controller: AppBundle:Admin:deleteUser}

response_new:
    path:     /response/{page}
    defaults: { _controller: AppBundle:Response:newCommentResponse}
response_delete:
    path:     /deleteresponse/{id}
    defaults: { _controller: AppBundle:Response:deleteCommentResponse}
response_edit:
    path:     /editresponse/{id}
    defaults: { _controller: AppBundle:Response:editCommentResponse}

comment_new:
    path:     /comment/{page}
    defaults: { _controller: AppBundle:Comment:newComment}
comment_list:
    path: /listComments
    defaults: { _controller: AppBundle:Comment:listComment}
comment_edit:
    path:     /editcomment/{id}
    defaults: { _controller: AppBundle:Comment:editComment}
comment_delete:
    path:     /deletecomment/{id}
    defaults: { _controller: AppBundle:Comment:deleteComment}


security_login:
    path:     /login
    defaults: { _controller: AppBundle:Security:login}
security_logout:
    path:     /logout
    defaults: { _controller: AppBundle:Security:login}

home:
    path:     /
    defaults: { _controller: AppBundle:Grunt:home }
grunt:
    path: /{pagina}/{id}
    defaults: { _controller: AppBundle:Grunt:show, id: null, page: null}









